/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`candlesticks`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CandlesticksError {
    Status400(models::ResultCode),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fundings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FundingsError {
    Status400(models::ResultCode),
    UnknownValue(serde_json::Value),
}


/// Get candlesticks
pub async fn candlesticks(configuration: &configuration::Configuration, market_id: i32, resolution: &str, start_timestamp: i64, end_timestamp: i64, count_back: i64, set_timestamp_to_end: Option<bool>) -> Result<models::Candlesticks, Error<CandlesticksError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_market_id = market_id;
    let p_query_resolution = resolution;
    let p_query_start_timestamp = start_timestamp;
    let p_query_end_timestamp = end_timestamp;
    let p_query_count_back = count_back;
    let p_query_set_timestamp_to_end = set_timestamp_to_end;

    let uri_str = format!("{}/api/v1/candlesticks", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("market_id", &p_query_market_id.to_string())]);
    req_builder = req_builder.query(&[("resolution", &p_query_resolution.to_string())]);
    req_builder = req_builder.query(&[("start_timestamp", &p_query_start_timestamp.to_string())]);
    req_builder = req_builder.query(&[("end_timestamp", &p_query_end_timestamp.to_string())]);
    req_builder = req_builder.query(&[("count_back", &p_query_count_back.to_string())]);
    if let Some(ref param_value) = p_query_set_timestamp_to_end {
        req_builder = req_builder.query(&[("set_timestamp_to_end", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Candlesticks`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Candlesticks`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CandlesticksError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get fundings
pub async fn fundings(configuration: &configuration::Configuration, market_id: i32, resolution: &str, start_timestamp: i64, end_timestamp: i64, count_back: i64) -> Result<models::Fundings, Error<FundingsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_market_id = market_id;
    let p_query_resolution = resolution;
    let p_query_start_timestamp = start_timestamp;
    let p_query_end_timestamp = end_timestamp;
    let p_query_count_back = count_back;

    let uri_str = format!("{}/api/v1/fundings", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("market_id", &p_query_market_id.to_string())]);
    req_builder = req_builder.query(&[("resolution", &p_query_resolution.to_string())]);
    req_builder = req_builder.query(&[("start_timestamp", &p_query_start_timestamp.to_string())]);
    req_builder = req_builder.query(&[("end_timestamp", &p_query_end_timestamp.to_string())]);
    req_builder = req_builder.query(&[("count_back", &p_query_count_back.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Fundings`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Fundings`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FundingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

