/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountLimits {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "max_llp_percentage")]
    pub max_llp_percentage: i32,
    #[serde(rename = "user_tier")]
    pub user_tier: String,
}

impl AccountLimits {
    pub fn new(code: i32, max_llp_percentage: i32, user_tier: String) -> AccountLimits {
        AccountLimits {
            code,
            message: None,
            max_llp_percentage,
            user_tier,
        }
    }
}

