/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Account {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "account_type")]
    pub account_type: i32,
    #[serde(rename = "index")]
    pub index: i64,
    #[serde(rename = "l1_address")]
    pub l1_address: String,
    #[serde(rename = "cancel_all_time")]
    pub cancel_all_time: i64,
    #[serde(rename = "total_order_count")]
    pub total_order_count: i64,
    #[serde(rename = "total_isolated_order_count")]
    pub total_isolated_order_count: i64,
    #[serde(rename = "pending_order_count")]
    pub pending_order_count: i64,
    #[serde(rename = "available_balance")]
    pub available_balance: String,
    #[serde(rename = "status")]
    pub status: i32,
    #[serde(rename = "collateral")]
    pub collateral: String,
}

impl Account {
    pub fn new(code: i32, account_type: i32, index: i64, l1_address: String, cancel_all_time: i64, total_order_count: i64, total_isolated_order_count: i64, pending_order_count: i64, available_balance: String, status: i32, collateral: String) -> Account {
        Account {
            code,
            message: None,
            account_type,
            index,
            l1_address,
            cancel_all_time,
            total_order_count,
            total_isolated_order_count,
            pending_order_count,
            available_balance,
            status,
            collateral,
        }
    }
}

