/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountMarginStats {
    #[serde(rename = "collateral")]
    pub collateral: String,
    #[serde(rename = "portfolio_value")]
    pub portfolio_value: String,
    #[serde(rename = "leverage")]
    pub leverage: String,
    #[serde(rename = "available_balance")]
    pub available_balance: String,
    #[serde(rename = "margin_usage")]
    pub margin_usage: String,
    #[serde(rename = "buying_power")]
    pub buying_power: String,
}

impl AccountMarginStats {
    pub fn new(collateral: String, portfolio_value: String, leverage: String, available_balance: String, margin_usage: String, buying_power: String) -> AccountMarginStats {
        AccountMarginStats {
            collateral,
            portfolio_value,
            leverage,
            available_balance,
            margin_usage,
            buying_power,
        }
    }
}

