/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountMetadata {
    #[serde(rename = "account_index")]
    pub account_index: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    ///  Remove After FE uses L1 meta endpoint
    #[serde(rename = "can_invite")]
    pub can_invite: bool,
    ///  Remove After FE uses L1 meta endpoint
    #[serde(rename = "referral_points_percentage")]
    pub referral_points_percentage: String,
}

impl AccountMetadata {
    pub fn new(account_index: i64, name: String, description: String, can_invite: bool, referral_points_percentage: String) -> AccountMetadata {
        AccountMetadata {
            account_index,
            name,
            description,
            can_invite,
            referral_points_percentage,
        }
    }
}

