/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountApiKeys {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "api_keys")]
    pub api_keys: Vec<models::ApiKey>,
}

impl AccountApiKeys {
    pub fn new(code: i32, api_keys: Vec<models::ApiKey>) -> AccountApiKeys {
        AccountApiKeys {
            code,
            message: None,
            api_keys,
        }
    }
}

