/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountMarketStats {
    #[serde(rename = "market_id")]
    pub market_id: i32,
    #[serde(rename = "daily_trades_count")]
    pub daily_trades_count: i64,
    #[serde(rename = "daily_base_token_volume")]
    pub daily_base_token_volume: f64,
    #[serde(rename = "daily_quote_token_volume")]
    pub daily_quote_token_volume: f64,
    #[serde(rename = "weekly_trades_count")]
    pub weekly_trades_count: i64,
    #[serde(rename = "weekly_base_token_volume")]
    pub weekly_base_token_volume: f64,
    #[serde(rename = "weekly_quote_token_volume")]
    pub weekly_quote_token_volume: f64,
    #[serde(rename = "monthly_trades_count")]
    pub monthly_trades_count: i64,
    #[serde(rename = "monthly_base_token_volume")]
    pub monthly_base_token_volume: f64,
    #[serde(rename = "monthly_quote_token_volume")]
    pub monthly_quote_token_volume: f64,
    #[serde(rename = "total_trades_count")]
    pub total_trades_count: i64,
    #[serde(rename = "total_base_token_volume")]
    pub total_base_token_volume: f64,
    #[serde(rename = "total_quote_token_volume")]
    pub total_quote_token_volume: f64,
}

impl AccountMarketStats {
    pub fn new(market_id: i32, daily_trades_count: i64, daily_base_token_volume: f64, daily_quote_token_volume: f64, weekly_trades_count: i64, weekly_base_token_volume: f64, weekly_quote_token_volume: f64, monthly_trades_count: i64, monthly_base_token_volume: f64, monthly_quote_token_volume: f64, total_trades_count: i64, total_base_token_volume: f64, total_quote_token_volume: f64) -> AccountMarketStats {
        AccountMarketStats {
            market_id,
            daily_trades_count,
            daily_base_token_volume,
            daily_quote_token_volume,
            weekly_trades_count,
            weekly_base_token_volume,
            weekly_quote_token_volume,
            monthly_trades_count,
            monthly_base_token_volume,
            monthly_quote_token_volume,
            total_trades_count,
            total_base_token_volume,
            total_quote_token_volume,
        }
    }
}

