/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountTradeStats {
    #[serde(rename = "daily_trades_count")]
    pub daily_trades_count: i64,
    #[serde(rename = "daily_volume")]
    pub daily_volume: f64,
    #[serde(rename = "weekly_trades_count")]
    pub weekly_trades_count: i64,
    #[serde(rename = "weekly_volume")]
    pub weekly_volume: f64,
    #[serde(rename = "monthly_trades_count")]
    pub monthly_trades_count: i64,
    #[serde(rename = "monthly_volume")]
    pub monthly_volume: f64,
    #[serde(rename = "total_trades_count")]
    pub total_trades_count: i64,
    #[serde(rename = "total_volume")]
    pub total_volume: f64,
}

impl AccountTradeStats {
    pub fn new(daily_trades_count: i64, daily_volume: f64, weekly_trades_count: i64, weekly_volume: f64, monthly_trades_count: i64, monthly_volume: f64, total_trades_count: i64, total_volume: f64) -> AccountTradeStats {
        AccountTradeStats {
            daily_trades_count,
            daily_volume,
            weekly_trades_count,
            weekly_volume,
            monthly_trades_count,
            monthly_volume,
            total_trades_count,
            total_volume,
        }
    }
}

