/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKey {
    #[serde(rename = "account_index")]
    pub account_index: i64,
    #[serde(rename = "api_key_index")]
    pub api_key_index: i32,
    #[serde(rename = "nonce")]
    pub nonce: i64,
    #[serde(rename = "public_key")]
    pub public_key: String,
}

impl ApiKey {
    pub fn new(account_index: i64, api_key_index: i32, nonce: i64, public_key: String) -> ApiKey {
        ApiKey {
            account_index,
            api_key_index,
            nonce,
            public_key,
        }
    }
}

