/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BridgeSupportedNetwork {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "chain_id")]
    pub chain_id: String,
    #[serde(rename = "explorer")]
    pub explorer: String,
}

impl BridgeSupportedNetwork {
    pub fn new(name: String, chain_id: String, explorer: String) -> BridgeSupportedNetwork {
        BridgeSupportedNetwork {
            name,
            chain_id,
            explorer,
        }
    }
}

