/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Candlestick {
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "open")]
    pub open: f64,
    #[serde(rename = "high")]
    pub high: f64,
    #[serde(rename = "low")]
    pub low: f64,
    #[serde(rename = "close")]
    pub close: f64,
    #[serde(rename = "volume0")]
    pub volume0: f64,
    #[serde(rename = "volume1")]
    pub volume1: f64,
    #[serde(rename = "last_trade_id")]
    pub last_trade_id: i64,
}

impl Candlestick {
    pub fn new(timestamp: i64, open: f64, high: f64, low: f64, close: f64, volume0: f64, volume1: f64, last_trade_id: i64) -> Candlestick {
        Candlestick {
            timestamp,
            open,
            high,
            low,
            close,
            volume0,
            volume1,
            last_trade_id,
        }
    }
}

