/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DailyReturn {
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "daily_return")]
    pub daily_return: f64,
}

impl DailyReturn {
    pub fn new(timestamp: i64, daily_return: f64) -> DailyReturn {
        DailyReturn {
            timestamp,
            daily_return,
        }
    }
}

