/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DepositHistory {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "deposits")]
    pub deposits: Vec<models::DepositHistoryItem>,
    #[serde(rename = "cursor")]
    pub cursor: String,
}

impl DepositHistory {
    pub fn new(code: i32, deposits: Vec<models::DepositHistoryItem>, cursor: String) -> DepositHistory {
        DepositHistory {
            code,
            message: None,
            deposits,
            cursor,
        }
    }
}

