/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Fundings {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "resolution")]
    pub resolution: String,
    #[serde(rename = "fundings")]
    pub fundings: Vec<models::Funding>,
}

impl Fundings {
    pub fn new(code: i32, resolution: String, fundings: Vec<models::Funding>) -> Fundings {
        Fundings {
            code,
            message: None,
            resolution,
            fundings,
        }
    }
}

