/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Funding {
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "rate")]
    pub rate: String,
    #[serde(rename = "direction")]
    pub direction: String,
}

impl Funding {
    pub fn new(timestamp: i64, value: String, rate: String, direction: String) -> Funding {
        Funding {
            timestamp,
            value,
            rate,
            direction,
        }
    }
}

