/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct L1Metadata {
    #[serde(rename = "l1_address")]
    pub l1_address: String,
    #[serde(rename = "can_invite")]
    pub can_invite: bool,
    #[serde(rename = "referral_points_percentage")]
    pub referral_points_percentage: String,
}

impl L1Metadata {
    pub fn new(l1_address: String, can_invite: bool, referral_points_percentage: String) -> L1Metadata {
        L1Metadata {
            l1_address,
            can_invite,
            referral_points_percentage,
        }
    }
}

