/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct L1ProviderInfo {
    #[serde(rename = "chainId")]
    pub chain_id: i64,
    #[serde(rename = "networkId")]
    pub network_id: i64,
    #[serde(rename = "latestBlockNumber")]
    pub latest_block_number: i64,
}

impl L1ProviderInfo {
    pub fn new(chain_id: i64, network_id: i64, latest_block_number: i64) -> L1ProviderInfo {
        L1ProviderInfo {
            chain_id,
            network_id,
            latest_block_number,
        }
    }
}

