/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiqTrade {
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "size")]
    pub size: String,
    #[serde(rename = "taker_fee")]
    pub taker_fee: String,
    #[serde(rename = "maker_fee")]
    pub maker_fee: String,
}

impl LiqTrade {
    pub fn new(price: String, size: String, taker_fee: String, maker_fee: String) -> LiqTrade {
        LiqTrade {
            price,
            size,
            taker_fee,
            maker_fee,
        }
    }
}

