/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiquidationInfos {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "liquidations")]
    pub liquidations: Vec<models::Liquidation>,
    #[serde(rename = "next_cursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

impl LiquidationInfos {
    pub fn new(code: i32, liquidations: Vec<models::Liquidation>) -> LiquidationInfos {
        LiquidationInfos {
            code,
            message: None,
            liquidations,
            next_cursor: None,
        }
    }
}

