/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderBookStats {
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "last_trade_price")]
    pub last_trade_price: f64,
    #[serde(rename = "daily_trades_count")]
    pub daily_trades_count: i64,
    #[serde(rename = "daily_base_token_volume")]
    pub daily_base_token_volume: f64,
    #[serde(rename = "daily_quote_token_volume")]
    pub daily_quote_token_volume: f64,
    #[serde(rename = "daily_price_change")]
    pub daily_price_change: f64,
}

impl OrderBookStats {
    pub fn new(symbol: String, last_trade_price: f64, daily_trades_count: i64, daily_base_token_volume: f64, daily_quote_token_volume: f64, daily_price_change: f64) -> OrderBookStats {
        OrderBookStats {
            symbol,
            last_trade_price,
            daily_trades_count,
            daily_base_token_volume,
            daily_quote_token_volume,
            daily_price_change,
        }
    }
}

