/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderBookOrders {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "total_asks")]
    pub total_asks: i64,
    #[serde(rename = "asks")]
    pub asks: Vec<models::SimpleOrder>,
    #[serde(rename = "total_bids")]
    pub total_bids: i64,
    #[serde(rename = "bids")]
    pub bids: Vec<models::SimpleOrder>,
}

impl OrderBookOrders {
    pub fn new(code: i32, total_asks: i64, asks: Vec<models::SimpleOrder>, total_bids: i64, bids: Vec<models::SimpleOrder>) -> OrderBookOrders {
        OrderBookOrders {
            code,
            message: None,
            total_asks,
            asks,
            total_bids,
            bids,
        }
    }
}

