/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderBookDepth {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "asks")]
    pub asks: Vec<models::PriceLevel>,
    #[serde(rename = "bids")]
    pub bids: Vec<models::PriceLevel>,
    #[serde(rename = "offset")]
    pub offset: i64,
}

impl OrderBookDepth {
    pub fn new(code: i32, asks: Vec<models::PriceLevel>, bids: Vec<models::PriceLevel>, offset: i64) -> OrderBookDepth {
        OrderBookDepth {
            code,
            message: None,
            asks,
            bids,
            offset,
        }
    }
}

