/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PnLEntry {
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "trade_pnl")]
    pub trade_pnl: f64,
    #[serde(rename = "inflow")]
    pub inflow: f64,
    #[serde(rename = "outflow")]
    pub outflow: f64,
    #[serde(rename = "pool_pnl")]
    pub pool_pnl: f64,
    #[serde(rename = "pool_inflow")]
    pub pool_inflow: f64,
    #[serde(rename = "pool_outflow")]
    pub pool_outflow: f64,
    #[serde(rename = "pool_total_shares")]
    pub pool_total_shares: f64,
}

impl PnLEntry {
    pub fn new(timestamp: i64, trade_pnl: f64, inflow: f64, outflow: f64, pool_pnl: f64, pool_inflow: f64, pool_outflow: f64, pool_total_shares: f64) -> PnLEntry {
        PnLEntry {
            timestamp,
            trade_pnl,
            inflow,
            outflow,
            pool_pnl,
            pool_inflow,
            pool_outflow,
            pool_total_shares,
        }
    }
}

