/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicPoolShare {
    #[serde(rename = "public_pool_index")]
    pub public_pool_index: i64,
    #[serde(rename = "shares_amount")]
    pub shares_amount: i64,
    #[serde(rename = "entry_usdc")]
    pub entry_usdc: String,
}

impl PublicPoolShare {
    pub fn new(public_pool_index: i64, shares_amount: i64, entry_usdc: String) -> PublicPoolShare {
        PublicPoolShare {
            public_pool_index,
            shares_amount,
            entry_usdc,
        }
    }
}

