/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferralPointEntry {
    #[serde(rename = "l1_address")]
    pub l1_address: String,
    #[serde(rename = "total_points")]
    pub total_points: i64,
    #[serde(rename = "week_points")]
    pub week_points: i64,
    #[serde(rename = "total_reward_points")]
    pub total_reward_points: i64,
    #[serde(rename = "week_reward_points")]
    pub week_reward_points: i64,
    #[serde(rename = "reward_point_multiplier")]
    pub reward_point_multiplier: String,
}

impl ReferralPointEntry {
    pub fn new(l1_address: String, total_points: i64, week_points: i64, total_reward_points: i64, week_reward_points: i64, reward_point_multiplier: String) -> ReferralPointEntry {
        ReferralPointEntry {
            l1_address,
            total_points,
            week_points,
            total_reward_points,
            week_reward_points,
            reward_point_multiplier,
        }
    }
}

