/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferralPoints {
    #[serde(rename = "referrals")]
    pub referrals: Vec<models::ReferralPointEntry>,
    #[serde(rename = "user_total_points")]
    pub user_total_points: i64,
    #[serde(rename = "user_last_week_points")]
    pub user_last_week_points: i64,
    #[serde(rename = "user_total_referral_reward_points")]
    pub user_total_referral_reward_points: i64,
    #[serde(rename = "user_last_week_referral_reward_points")]
    pub user_last_week_referral_reward_points: i64,
    #[serde(rename = "reward_point_multiplier")]
    pub reward_point_multiplier: String,
}

impl ReferralPoints {
    pub fn new(referrals: Vec<models::ReferralPointEntry>, user_total_points: i64, user_last_week_points: i64, user_total_referral_reward_points: i64, user_last_week_referral_reward_points: i64, reward_point_multiplier: String) -> ReferralPoints {
        ReferralPoints {
            referrals,
            user_total_points,
            user_last_week_points,
            user_total_referral_reward_points,
            user_last_week_referral_reward_points,
            reward_point_multiplier,
        }
    }
}

