/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetTransferFeeInfo {
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<String>,
    #[serde(rename = "account_index")]
    pub account_index: i64,
    #[serde(rename = "to_account_index", skip_serializing_if = "Option::is_none")]
    pub to_account_index: Option<i64>,
}

impl ReqGetTransferFeeInfo {
    pub fn new(account_index: i64) -> ReqGetTransferFeeInfo {
        ReqGetTransferFeeInfo {
            auth: None,
            account_index,
            to_account_index: None,
        }
    }
}

