/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetDepositHistory {
    #[serde(rename = "account_index")]
    pub account_index: i64,
    ///  made optional to support header auth clients
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<String>,
    #[serde(rename = "l1_address")]
    pub l1_address: String,
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Filter>,
}

impl ReqGetDepositHistory {
    pub fn new(account_index: i64, l1_address: String) -> ReqGetDepositHistory {
        ReqGetDepositHistory {
            account_index,
            auth: None,
            l1_address,
            cursor: None,
            filter: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Filter {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "claimable")]
    Claimable,
}

impl Default for Filter {
    fn default() -> Filter {
        Self::All
    }
}

