/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetL1Metadata {
    ///  made optional to support header auth clients
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<String>,
    #[serde(rename = "l1_address")]
    pub l1_address: String,
}

impl ReqGetL1Metadata {
    pub fn new(l1_address: String) -> ReqGetL1Metadata {
        ReqGetL1Metadata {
            auth: None,
            l1_address,
        }
    }
}

