/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetAccountLimits {
    #[serde(rename = "account_index")]
    pub account_index: i64,
    ///  made optional to support header auth clients
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<String>,
}

impl ReqGetAccountLimits {
    pub fn new(account_index: i64) -> ReqGetAccountLimits {
        ReqGetAccountLimits {
            account_index,
            auth: None,
        }
    }
}

