/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetBlockTxs {
    #[serde(rename = "by")]
    pub by: By,
    #[serde(rename = "value")]
    pub value: String,
}

impl ReqGetBlockTxs {
    pub fn new(by: By, value: String) -> ReqGetBlockTxs {
        ReqGetBlockTxs {
            by,
            value,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum By {
    #[serde(rename = "block_height")]
    BlockHeight,
    #[serde(rename = "block_commitment")]
    BlockCommitment,
}

impl Default for By {
    fn default() -> By {
        Self::BlockHeight
    }
}

