/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetAccountApiKeys {
    #[serde(rename = "account_index")]
    pub account_index: i64,
    #[serde(rename = "api_key_index", skip_serializing_if = "Option::is_none")]
    pub api_key_index: Option<i32>,
}

impl ReqGetAccountApiKeys {
    pub fn new(account_index: i64) -> ReqGetAccountApiKeys {
        ReqGetAccountApiKeys {
            account_index,
            api_key_index: None,
        }
    }
}

