/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetAccountInactiveOrders {
    ///  made optional to support header auth clients
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<String>,
    #[serde(rename = "account_index")]
    pub account_index: i64,
    #[serde(rename = "market_id", skip_serializing_if = "Option::is_none")]
    pub market_id: Option<i32>,
    #[serde(rename = "ask_filter", skip_serializing_if = "Option::is_none")]
    pub ask_filter: Option<i32>,
    #[serde(rename = "between_timestamps", skip_serializing_if = "Option::is_none")]
    pub between_timestamps: Option<String>,
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    pub limit: i64,
}

impl ReqGetAccountInactiveOrders {
    pub fn new(account_index: i64, limit: i64) -> ReqGetAccountInactiveOrders {
        ReqGetAccountInactiveOrders {
            auth: None,
            account_index,
            market_id: None,
            ask_filter: None,
            between_timestamps: None,
            cursor: None,
            limit,
        }
    }
}

