/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetRecentTrades {
    #[serde(rename = "market_id")]
    pub market_id: i32,
    #[serde(rename = "limit")]
    pub limit: i64,
}

impl ReqGetRecentTrades {
    pub fn new(market_id: i32, limit: i64) -> ReqGetRecentTrades {
        ReqGetRecentTrades {
            market_id,
            limit,
        }
    }
}

