/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetAccountActiveOrders {
    #[serde(rename = "account_index")]
    pub account_index: i64,
    #[serde(rename = "market_id")]
    pub market_id: i32,
    ///  made optional to support header auth clients
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<String>,
}

impl ReqGetAccountActiveOrders {
    pub fn new(account_index: i64, market_id: i32) -> ReqGetAccountActiveOrders {
        ReqGetAccountActiveOrders {
            account_index,
            market_id,
            auth: None,
        }
    }
}

