/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetRangeWithCursor {
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    pub limit: i64,
}

impl ReqGetRangeWithCursor {
    pub fn new(limit: i64) -> ReqGetRangeWithCursor {
        ReqGetRangeWithCursor {
            cursor: None,
            limit,
        }
    }
}

