/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetL1Tx {
    #[serde(rename = "hash")]
    pub hash: String,
}

impl ReqGetL1Tx {
    pub fn new(hash: String) -> ReqGetL1Tx {
        ReqGetL1Tx {
            hash,
        }
    }
}

