/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetRangeWithIndex {
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<i64>,
    #[serde(rename = "limit")]
    pub limit: i64,
}

impl ReqGetRangeWithIndex {
    pub fn new(limit: i64) -> ReqGetRangeWithIndex {
        ReqGetRangeWithIndex {
            index: None,
            limit,
        }
    }
}

