/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetCandlesticks {
    #[serde(rename = "market_id")]
    pub market_id: i32,
    #[serde(rename = "resolution")]
    pub resolution: Resolution,
    #[serde(rename = "start_timestamp")]
    pub start_timestamp: i64,
    #[serde(rename = "end_timestamp")]
    pub end_timestamp: i64,
    #[serde(rename = "count_back")]
    pub count_back: i64,
    #[serde(rename = "set_timestamp_to_end", skip_serializing_if = "Option::is_none")]
    pub set_timestamp_to_end: Option<bool>,
}

impl ReqGetCandlesticks {
    pub fn new(market_id: i32, resolution: Resolution, start_timestamp: i64, end_timestamp: i64, count_back: i64) -> ReqGetCandlesticks {
        ReqGetCandlesticks {
            market_id,
            resolution,
            start_timestamp,
            end_timestamp,
            count_back,
            set_timestamp_to_end: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Resolution {
    #[serde(rename = "1m")]
    Variant1m,
    #[serde(rename = "5m")]
    Variant5m,
    #[serde(rename = "15m")]
    Variant15m,
    #[serde(rename = "1h")]
    Variant1h,
    #[serde(rename = "4h")]
    Variant4h,
    #[serde(rename = "1d")]
    Variant1d,
}

impl Default for Resolution {
    fn default() -> Resolution {
        Self::Variant1m
    }
}

