/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetNextNonce {
    #[serde(rename = "account_index")]
    pub account_index: i64,
    #[serde(rename = "api_key_index")]
    pub api_key_index: i32,
}

impl ReqGetNextNonce {
    pub fn new(account_index: i64, api_key_index: i32) -> ReqGetNextNonce {
        ReqGetNextNonce {
            account_index,
            api_key_index,
        }
    }
}

