/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetAccountByL1Address {
    #[serde(rename = "l1_address")]
    pub l1_address: String,
}

impl ReqGetAccountByL1Address {
    pub fn new(l1_address: String) -> ReqGetAccountByL1Address {
        ReqGetAccountByL1Address {
            l1_address,
        }
    }
}

