/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqGetAccountMetadata {
    #[serde(rename = "by")]
    pub by: By,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<String>,
}

impl ReqGetAccountMetadata {
    pub fn new(by: By, value: String) -> ReqGetAccountMetadata {
        ReqGetAccountMetadata {
            by,
            value,
            auth: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum By {
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "l1_address")]
    L1Address,
}

impl Default for By {
    fn default() -> By {
        Self::Index
    }
}

