/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RespWithdrawalDelay {
    #[serde(rename = "seconds")]
    pub seconds: i64,
}

impl RespWithdrawalDelay {
    pub fn new(seconds: i64) -> RespWithdrawalDelay {
        RespWithdrawalDelay {
            seconds,
        }
    }
}

