/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RespGetFastBridgeInfo {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "fast_bridge_limit")]
    pub fast_bridge_limit: String,
}

impl RespGetFastBridgeInfo {
    pub fn new(code: i32, fast_bridge_limit: String) -> RespGetFastBridgeInfo {
        RespGetFastBridgeInfo {
            code,
            message: None,
            fast_bridge_limit,
        }
    }
}

