/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RespPublicPoolsMetadata {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "public_pools")]
    pub public_pools: Vec<models::PublicPoolMetadata>,
}

impl RespPublicPoolsMetadata {
    pub fn new(code: i32, public_pools: Vec<models::PublicPoolMetadata>) -> RespPublicPoolsMetadata {
        RespPublicPoolsMetadata {
            code,
            message: None,
            public_pools,
        }
    }
}

