/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RespChangeAccountTier {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl RespChangeAccountTier {
    pub fn new(code: i32) -> RespChangeAccountTier {
        RespChangeAccountTier {
            code,
            message: None,
        }
    }
}

