/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RespSendTx {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "tx_hash")]
    pub tx_hash: String,
    #[serde(rename = "predicted_execution_time_ms")]
    pub predicted_execution_time_ms: i64,
}

impl RespSendTx {
    pub fn new(code: i32, tx_hash: String, predicted_execution_time_ms: i64) -> RespSendTx {
        RespSendTx {
            code,
            message: None,
            tx_hash,
            predicted_execution_time_ms,
        }
    }
}

