/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskParameters {
    #[serde(rename = "market_id")]
    pub market_id: i32,
    #[serde(rename = "collateral")]
    pub collateral: String,
    #[serde(rename = "total_account_value")]
    pub total_account_value: String,
    #[serde(rename = "initial_margin_req")]
    pub initial_margin_req: String,
    #[serde(rename = "maintenance_margin_req")]
    pub maintenance_margin_req: String,
    #[serde(rename = "close_out_margin_req")]
    pub close_out_margin_req: String,
}

impl RiskParameters {
    pub fn new(market_id: i32, collateral: String, total_account_value: String, initial_margin_req: String, maintenance_margin_req: String, close_out_margin_req: String) -> RiskParameters {
        RiskParameters {
            market_id,
            collateral,
            total_account_value,
            initial_margin_req,
            maintenance_margin_req,
            close_out_margin_req,
        }
    }
}

