/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskInfo {
    #[serde(rename = "cross_risk_parameters")]
    pub cross_risk_parameters: Box<models::RiskParameters>,
    #[serde(rename = "isolated_risk_parameters")]
    pub isolated_risk_parameters: Vec<models::RiskParameters>,
}

impl RiskInfo {
    pub fn new(cross_risk_parameters: models::RiskParameters, isolated_risk_parameters: Vec<models::RiskParameters>) -> RiskInfo {
        RiskInfo {
            cross_risk_parameters: Box::new(cross_risk_parameters),
            isolated_risk_parameters,
        }
    }
}

