/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SharePrice {
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "share_price")]
    pub share_price: f64,
}

impl SharePrice {
    pub fn new(timestamp: i64, share_price: f64) -> SharePrice {
        SharePrice {
            timestamp,
            share_price,
        }
    }
}

