/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Status {
    #[serde(rename = "status")]
    pub status: i32,
    #[serde(rename = "network_id")]
    pub network_id: i32,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
}

impl Status {
    pub fn new(status: i32, network_id: i32, timestamp: i64) -> Status {
        Status {
            status,
            network_id,
            timestamp,
        }
    }
}

