/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubAccounts {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "l1_address")]
    pub l1_address: String,
    #[serde(rename = "sub_accounts")]
    pub sub_accounts: Vec<models::Account>,
}

impl SubAccounts {
    pub fn new(code: i32, l1_address: String, sub_accounts: Vec<models::Account>) -> SubAccounts {
        SubAccounts {
            code,
            message: None,
            l1_address,
            sub_accounts,
        }
    }
}

