/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ticker {
    #[serde(rename = "s")]
    pub s: String,
    #[serde(rename = "a")]
    pub a: Box<models::PriceLevel>,
    #[serde(rename = "b")]
    pub b: Box<models::PriceLevel>,
}

impl Ticker {
    pub fn new(s: String, a: models::PriceLevel, b: models::PriceLevel) -> Ticker {
        Ticker {
            s,
            a: Box::new(a),
            b: Box::new(b),
        }
    }
}

