/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferFeeInfo {
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "transfer_fee_usdc")]
    pub transfer_fee_usdc: i64,
}

impl TransferFeeInfo {
    pub fn new(code: i32, transfer_fee_usdc: i64) -> TransferFeeInfo {
        TransferFeeInfo {
            code,
            message: None,
            transfer_fee_usdc,
        }
    }
}

