/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatorInfo {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "is_active")]
    pub is_active: bool,
}

impl ValidatorInfo {
    pub fn new(address: String, is_active: bool) -> ValidatorInfo {
        ValidatorInfo {
            address,
            is_active,
        }
    }
}

