/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawHistoryItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "l1_tx_hash")]
    pub l1_tx_hash: String,
}

impl WithdrawHistoryItem {
    pub fn new(id: String, amount: String, timestamp: i64, status: Status, r#type: Type, l1_tx_hash: String) -> WithdrawHistoryItem {
        WithdrawHistoryItem {
            id,
            amount,
            timestamp,
            status,
            r#type,
            l1_tx_hash,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "claimable")]
    Claimable,
    #[serde(rename = "refunded")]
    Refunded,
    #[serde(rename = "completed")]
    Completed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Failed
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "secure")]
    Secure,
    #[serde(rename = "fast")]
    Fast,
}

impl Default for Type {
    fn default() -> Type {
        Self::Secure
    }
}

