/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ZkLighterInfo {
    #[serde(rename = "contract_address")]
    pub contract_address: String,
}

impl ZkLighterInfo {
    pub fn new(contract_address: String) -> ZkLighterInfo {
        ZkLighterInfo {
            contract_address,
        }
    }
}

